name = "citatype"
main = "src/worker.ts"
compatibility_date = "2025-01-01"

vars = { ENVIRONMENT = "production" }

[assets]
directory = "public"

[env.preview]
vars = { ENVIRONMENT = "preview" }

[env.local]
vars = { ENVIRONMENT = "local" }
